### ISSUE TITLE
Question about README.md file

### ISSUE THREAD

**Issue by fojensen** [greyxray/TauAnalysisTools#2]
I have a question regarding "Step 2" in the README.md file in the CMSSW_10_4_0_pre3_tau-pog_RunIIAutumn18MiniAOD branch:
https://github.com/greyxray/TauAnalysisTools/blob/CMSSW_10_4_0_pre3_tau-pog_RunIIAutumn18MiniAOD/README.md

Step 2 says to:
`python produceTauIdMVATrainingNtupleMiniAOD_cfg.py`

I am guessing, from CMSSW_10_4_0_pre3/src/, we need to actually call
`python TauAnalysisTools/TauAnalysisTools/test/produceTauIdMVATrainingNtupleMiniAOD_cfg.py`

Although when I run it, I get the following error:
`ImportError: No module named TauAnalysisTools.TauAnalysisTools.runTauIdMVA`

The file is there, because
`ls TauAnalysisTools/TauAnalysisTools/python/runTauIdMVA.py`
works.

I am guessing this is something very simple I am overlooking...
Thank You.

**Comment by greyxray** [comment]
Hi Frank, have you done `scram b` after cloning the repository?

**Comment by fojensen** [comment]
Ohh shucks - I should have known better, that is almost the equivalent of making sure your broken electronics are even plugged in.

thanks...
